### ISSUE TITLE
Libquic to-do

### ISSUE THREAD

**Issue by dr7ana** [oxen-io/oxen-libquic#29]
TODO:
- [x] ZMQ bridge - #32
- [x] close handling - #33
- [x] rework datagram buffers part 1 - #28
- [x] rework datagram buffers part 2
- [x] wrap callbacks, review return values, etc
- [x] configure literal vs view for data hand-off
- [x] handling I/O error closing - #33
- [x] configure build to use local dependencies (`oxenc`, `oxen-logging`, `ngtcp2`, etc) - #25
